# Generated by Django 5.0.3 on 2024-03-14 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('c_name', models.CharField(max_length=50)),
                ('c_image', models.ImageField(default='category.jpg', upload_to='category')),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('sub_name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(db_column='cid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.category')),
            ],
        ),
    ]
