# Generated by Django 5.0.3 on 2024-03-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_c_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
