# Generated by Django 5.0.3 on 2024-05-09 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cartitem_is_deleted_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='p_id',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
