# Generated by Django 5.0.3 on 2024-03-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_is_listed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='parent_category',
        ),
    ]
