# Generated by Django 5.0.3 on 2024-07-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cartorder_options_cartorder_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='ip',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Razorpay', 'Razorpay'), ('Wallet', 'Wallet')], default='COD', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
