# Generated by Django 5.0.3 on 2024-03-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_category_subcategory_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_listed',
        ),
    ]
