# Generated by Django 5.0.3 on 2024-07-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_cartorder_payment_remove_productorder_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sub_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
