# Generated by Django 5.0.3 on 2024-05-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='latest',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='popular',
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=True),
        ),
    ]
