# Generated by Django 5.0.3 on 2024-03-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_category_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
