# Generated by Django 5.0.3 on 2024-07-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cartitem_sub_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='product',
            new_name='productt',
        ),
    ]
