# Generated by Django 5.0.3 on 2024-07-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_product_productorder_productt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='productt',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='sub_price',
        ),
    ]
