# Generated by Django 5.0.3 on 2024-03-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
