# Generated by Django 5.0.3 on 2024-03-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
