# Generated by Django 5.0.3 on 2024-07-19 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_wallet_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
