# Generated by Django 5.0.3 on 2024-08-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_returnreason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnreason',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='returnreason',
            name='reason',
        ),
        migrations.AddField(
            model_name='returnreason',
            name='customer_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnreason',
            name='damaged_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnreason',
            name='delivery_delays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnreason',
            name='incorrect_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnreason',
            name='other_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnreason',
            name='sizing_issues',
            field=models.BooleanField(default=False),
        ),
    ]
