# Generated by Django 5.0.3 on 2024-06-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_categoryoffer_subcategoryoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_percentage',
            field=models.PositiveIntegerField(help_text='discount in percentage'),
        ),
    ]
