# Generated by Django 5.0.3 on 2024-03-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_images_productimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='generic_directory_path'),
        ),
    ]
