# Generated by Django 5.0.3 on 2024-08-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='wallet_balance_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
