# Generated by Django 5.0.3 on 2024-03-16 08:05

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_productimages_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to=store.models.generic_directory_path),
        ),
    ]
