# Generated by Django 5.0.3 on 2024-03-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_productimages_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image',
        ),
        migrations.AddField(
            model_name='productimages',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
