# Generated by Django 5.0.3 on 2024-09-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_cartorder_return_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='order_address',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>', max_length=100),
        ),
    ]
