# Generated by Django 5.0.3 on 2024-09-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_cartorder_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_address',
            field=models.CharField(max_length=100),
        ),
    ]
