# Generated by Django 5.0.3 on 2024-09-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_cartorder_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='size',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
