# Generated by Django 5.0.3 on 2024-04-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.TextField(null=True),
        ),
    ]
