# Generated by Django 5.0.3 on 2024-04-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_product_add_details_product_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='add_details',
        ),
    ]
