# Generated by Django 5.0.3 on 2024-04-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_remove_product_add_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantimages',
            name='images',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='VariantImages',
        ),
    ]
