# Generated by Django 5.0.3 on 2024-04-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_variantimages_images_delete_productvariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Size',
            field=models.ManyToManyField(null=True, to='store.size'),
        ),
    ]
