# Generated by Django 5.0.3 on 2024-04-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='price_increment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=50),
        ),
    ]
