# Generated by Django 5.0.3 on 2024-04-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_size_price_increment_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.ManyToManyField(blank=True, to='store.size'),
        ),
    ]
