# Generated by Django 5.0.3 on 2024-04-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
