# Generated by Django 5.0.3 on 2024-04-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='Medium', max_length=50),
            preserve_default=False,
        ),
    ]
