# Generated by Django 5.0.3 on 2024-07-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_userform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
