# Generated by Django 5.0.3 on 2024-08-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_wallethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
