# Generated by Django 5.0.3 on 2024-08-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_wallethistory_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='points',
        ),
    ]
