# Generated by Django 5.0.3 on 2024-09-08 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_referral_referral_code_remove_wallet_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referred',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='referral',
            name='my_referral',
            field=models.TextField(blank=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='referral',
            name='reffered_code',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
